### ISSUE TITLE
Нямам права

### ISSUE THREAD

**Issue by orliin** [yurukov/lawbrew#6]
Клонирах си repo-то, направих branch с малка промяна и пробвам да го push-на, за да пусна pull request, но ми дава грешка:
```
Pushing to github.com:yurukov/lawbrew.git
ERROR: Permission to yurukov/lawbrew.git denied to orliin.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by hkdobrev** [comment]
@orliin Опитваш се да го push-неш директно в yurukov/lawbrew. Правилното нещо е да го push-неш в твоя fork. Пробвай Fork бутона горе вдясно и от там работи с твоето хранилище - orliin/lawbrew. Там можеш да правиш бранчове и да го push-неш и от там ще направиш Pull request към оригиналното хранилище или т.нар. - upstream.

**Comment by yurukov** [comment]
@hkdobrev е прав. Няма процес още за права на основния проект. За сега през fork ще е.
